name: Matrix
on: push
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: $
    steps:
      
      - name: Build
        run: echo ${{matrix.os}}
